# Configuration file for the quant trading pipeline
# All paths are relative to the project root directory

# Projeto
project:
  name: quant-pipeline
  base_timezone: America/Sao_Paulo

data:
  source: brapi
  path_raw: data/raw
  path_processed: data/processed

# Mercado e Ativos
market:
  assets:
    - Ë†BVSP
    - ABEV3
    - AERI3
    - ALPA4
    - AMER3
    - AZUL4
    - B3SA3
    - BBAS3
    - BBDC4
    - BBSE3
    - BEEF3
    - BMGB4
    - BPAC11
    - BRAP4
    - BRFS3
    - BRKM5
    - BRSR6
    - CAML3
    - CASH3
    - CEAB3
    - CMIN3
    - COGN3
    - CPFE3
    - CPLE3
    - CPLE6
    - CSNA3
    - CVCB3
    - CYRE3
    - DIRR3
    - DXCO3
    - EGIE3
    - ELET3
    - ELET6
    - EMBR3
    - ENEV3
    - ENGI11
    - EZTC3
    - FESA4
    - GGBR4
    - GOAU4
    - GUAR3
    - HAPV3
    - HYPE3
    - ITSA4
    - ITUB4
    - JHSF3
    - KEPL3
    - KLBN11
    - LEVE3
    - LIGT3
    - LOGG3
    - LREN3
    - LWSA3
    - MEAL3
    - MGLU3
    - MOVI3
    - MRFG3
    - MRVE3
    - MULT3
    - NEOE3
    - PETR3
    - PETR4
    - PETZ3
    - POMO4
    - POSI3
    - PRIO3
    - PSSA3
    - QUAL3
    - RADL3
    - RECV3
    - RENT3
    - ROMI3
    - SANB11
    - SAPR11
    - SBSP3
    - SEER3
    - SHOW3
    - SLCE3
    - SOJA3
    - SUZB3
    - TAEE11
    - TEND3
    - TIMS3
    - TOTS3
    - UGPA3
    - UNIP6
    - USIM5
    - VALE3
    - VBBR3
    - VIVA3
    - VIVT3
    - VULC3
    - WEGE3
    - YDUQ3
    - CYRE3
    - EZTC3
    - MRFG3
    - JHSF3
    - BRAP4
    - SANB11
    - BPAC11
    - SMLS3
    - ALPA4
    - RENT3
    - MOVI3
    - LWSA3
    - CMIN3
    - PETZ3
    - ARZZ3
    - VIVT3
    - ENEV3
    - TRPL4
    - TAEE11
    - SBSP3
    - SLCE3
    - TOTS3
    - USIM5
    - GOAU4
    - BRKM5
    - UGPA3
    - DIRR3
    - PSSA3
    - BBSE3
    - BIDI11
    - SOJA3
    - RECV3
    - CASH3
    - DXCO3
    - NEOE3
    - CPLE6
    - AESB3
    - MEAL3
    - AERI3
    - CPLE3
    - ENGI11
    - SAPR11
    - GUAR3
    - LOGG3
    - BMGB4
    - TEND3
    - POSI3
    - ROMI3
    - FESA4
    - LEVE3
    - CAML3
    - POMO4
    - KEPL3
    - UNIP6
    - BRSR6
    - CEAB3
    - LIGT3
    - VULC3
    - SHOW3
    - VIVA3
    - SEER3
    - GUAR4
    